### PR TITLE
Only render color on white spaces or tabs

### LINKED ISSUE #81: Indentation color includes text characters
After disabling the error color for multi line statements the indentation color includes several characters of text to make a "full" indent color.
image

### PR DESCRIPTION
**Pull request by Fubuchi**
Fix #81

### CODE REVIEW

**Comment by oderwat** [comment]
As I wrote in #81, the behavior is intended. I am open to an optional configuration for such a feature but won't accept a default behavior change.

**Comment by Fubuchi** [comment]
Update with configuration added.

**Comment by oderwat** [comment]
Thank you. Will merge and create a new release soon!

**Comment by oderwat** [comment]
New release is out (7.5.0).

**Pull request merged**
