### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by gavindinubilo**
I believe this should help with #6 

This PR lets you set `colors` to be any size instead of the currently constricted 4. Also adds an `error_color` config option.

- Adds an error_color config option
- Makes it so colors config option can be any size you'd like
- Minor code optimizations
- Makes code comply with TSLint

### CODE REVIEW

**Comment by oderwat** [comment]
Looks cool. Thank you! I am going to merge and test it at the weekend and create and updated package afterwards.

**Comment by ChrisJefferson** [comment]
*ping*, is there any chance of this being merged and a new release made? I'd like the variable-sized colors array myself :)

Thanks for the package!

**Comment by Pszek** [comment]
@oderwat What is the status? When can we expect the merge? Btw. very nice extension, which helped me to ignore the hatred for indentation with spaces. Good job!

**Comment by oderwat** [comment]
I finally had time to merge and publish this PR. Sorry for being so slow and thank you for the cool PR!

**Comment by rchanou** [comment]
Awesome! Some trivial nits: it would be more conventional to camelCase to "errorColor", and I also still get the green underline with "Unknown configuration setting" even though it works. 

Still works great, thanks!

**Pull request merged**
