### PR TITLE
Enable your extension to run on VS Code for the web

### PR DESCRIPTION
**Pull request by tanhakabir**
Hey @oderwat! 👋

I'm part of the VS Code team and we recently launched VS Code for the web with [github.dev](https://docs.github.com/en/codespaces/developing-in-codespaces/web-based-editor)! You can read the full guide for extension authors creating and migrating extensions here: [Web Extensions
](https://code.visualstudio.com/api/extension-guides/web-extensions)

In hopes to help you migrate I helped make the changes necessary to make your extensions work on the web.

The changes I made:
- Added webpack bundling to bundle your extension into 1 JavaScript file for the web
- Added the compile scripts for webpack to your `package.json`
- Added the necessary dependencies for bundling
- Added the `browser` entry point to your `package.json` to link to the web-friendly compiled extension
- Updated VS Code tasks to the latest version

### CODE REVIEW

**Comment by oderwat** [comment]
Hey @tanhakabir,

Thank you for your contribution. I am going to check out your changes and github.dev very soon.

**Comment by oderwat** [comment]
I think it needs to be `"vscode:prepublish": "npm run compile && npm run package-web"` but I merged it and try to check and publish it.

**Comment by tanhakabir** [comment]
oh you're right! I added it to the list of scripts last minute

**Comment by oderwat** [comment]
I figured that was just a fluke. I already could publish the extension with the web functionality working. Nothing to do really, but your modifications helped a lot. One suggestion would be that you include a quick description of how to test locally if the extension works. 

I basically had to:

```
npm install @vscode/test-web
```

and then:

```
npx vscode-test-web --browserType=chromium --extensionDevelopmentPath=.
```

Didn't figure it out very quickly as I am not up to date with developing extensions lately.

**Comment by tanhakabir** [comment]
Good catch! Also thanks for the feedback! I'll add this to my PR messages :)

**Pull request merged**
