### PR TITLE
Fixed issue where highlight overlapped text

### PR DESCRIPTION
**Pull request by gbrunow**
Alternative to PR #92.

### CODE REVIEW

**Comment by gbrunow** [comment]
Hold on, I was trying to remove styling changes and messed it up.

**Comment by oderwat** [comment]
I guess you mean PR #91. 

I think that one may not need to summon math.min() for every line. I guess it will be faster as `if(shrinkBars && n > l) n=l`.

**Review by Oleksandr1201vsp — CHANGES_REQUESTED** [review]
extension.ts

**Review by Oleksandr1201vsp — CHANGES_REQUESTED** [review]
extension.ts

**Comment by oderwat** [comment]
Implemented through #98

**Pull request closed without merging**
